import Head from "next/head";
import { Inter } from "@next/font/google";
import { Box, Heading, Text } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ surah }) {
  return (
    <>
      <Head>
        <title>E-Qur'an</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box px={[4, 8]} py={8}>
        <Box maxW="800px" mx="auto">
          <Heading as="h1" size="3xl" mb={4} textAlign="center">
            Al-Qur'an
          </Heading>
          <Text fontSize="2xl" mb={8} textAlign="center">
            Bismillahirrahmanirrahim
          </Text>

          {/* List of surah */}
          <Box>
            <Heading as="h2" size="2xl" mb={8}>
              Daftar Surah
            </Heading>
            <Box>
              {/* map through list of surah */}
              {surah.map((s) => (
                <Box
                  key={s.nomor}
                  display="flex"
                  alignItems="center"
                  py={2}
                  borderBottom="1px solid"
                  borderBottomColor="gray.200"
                >
                  <Box w="20px" textAlign="center" fontWeight="bold">
                    {s.nomor}
                  </Box>
                  <Text ml={4}>{s.nama}</Text>
                </Box>
              ))}
            </Box>
          </Box>
        </Box>
      </Box>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch("https://equran.id/api/v2/surat");
  const data = await res.json();

  return {
    props: {
      surah: data.data,
    },
  };
}
